### ISSUE TITLE
invisible characters

### ISSUE THREAD

**Issue by revelt** [peterpeterparker/daviddalbusco.com#42]
hi David,

Thank you for the article, I was troubleshooting some Rollup + TS code of mine and stumbled upon your article (which helped, thank you) and noticed two things there:

## 1. Invisible characters in the raw markdown sources

There are raw invisible characters in the markdown. For example, in https://github.com/peterpeterparker/daviddalbusco.com/blob/master/src/blog/sometimes-you-just-need-a-dumb-library.md there is a BACKSPACE, [`\u8`](http://www.fileformat.info/info/unicode/char/8/index.htm), visible even on GitHub GUI:

![Screenshot 2020-11-08 at 17 07 17](https://user-images.githubusercontent.com/8344688/98471746-565c0d00-21e6-11eb-9c9b-86f3f0fff1c1.png)

If you wonder how am I able to identify culprits, I paste code into https://detergent.io of mine, it shows invisibles as red clickable bullets (under scenes that's Code Mirror doing the heavy lifting, I set a regex in its config to catch all characters that trim to zero length). 

In theory, you could find-and-replace on all blog post markdown files with a regex. Long-term, a plugin in your code editor to highlight invisibles would help too, for example, VSCode's Highlight Bad Chars, https://marketplace.visualstudio.com/items?itemName=wengerk.highlight-bad-chars or Atom's https://atom.io/packages/highlight-bad-chars or similar, whatever code editor you use.

## 2. Invisible characters in the generated HTML

There is also more serious problem with how your Gatsby setup renders code blocks into HTML. The same article, https://github.com/peterpeterparker/daviddalbusco.com/blob/master/src/blog/sometimes-you-just-need-a-dumb-library.md is rendered with [`\u200b`](https://www.fileformat.info/info/unicode/char/200b), very visible when copy-pasted into Detergent:

![Screenshot 2020-11-08 at 16 56 44](https://user-images.githubusercontent.com/8344688/98471739-493f1e00-21e6-11eb-8d0c-1941205cbf75.png)

The `\u200b` don't exist in the markdown source, Gatsby is adding them!

Rollup freaks out when I copy paste the code and errors until invisibles are removed:

<img width="407" alt="Screenshot 2020-11-08 at 17 19 25" src="https://user-images.githubusercontent.com/8344688/98471806-b3f05980-21e6-11eb-9d51-72447808beca.png">

So the code examples do work but with "a catch". My Gatsby is limited and my own projects use Eleventy so you'll have to find the exact cause and solution yourself.

**PS.** There's also good invisible character inspector web app, https://apps.timwhitlock.info/unicode/inspect/hex/1F1EC/1F1E7

All the best and greetings from UK!

**Comment by peterpeterparker** [comment]
Hey @revelt  thx a lot for the sweet issue and heads up! Took me time to answer, sorry for that and thx for your time, really appreciated.

I've pushed some fix in commit [029b656](https://github.com/peterpeterparker/daviddalbusco.com/commit/029b656d7c48030adfc31e5cc76d5b5dbe157d1d) I hope it fixes most of the invisible characters (result of a plugin I am using to export Markdown from Medium). I'll keep an eye on it.

**Comment by revelt** [comment]
No worries! The `\u200b` which Medium inserts belong to Medium Support, probably will never get fixed so let's close this ticket. Have a great day!

**Comment by peterpeterparker** [comment]
Most probably, thx again and have a great day too!
